FROM python:3.9.10-slim-buster

WORKDIR /python-docker

RUN apt-get update -y
RUN apt-get install -y libssl-dev
RUN apt-get install -y python3-dev default-libmysqlclient-dev
RUN apt-get install -y gcc

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .

EXPOSE 5000
CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0", "--port","5000"]