apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-api
  namespace: virtu-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-api
  template:
    metadata:
      labels:
        app: quiz-api
    spec:
      containers:
        - image: damienesiee/quiz-api:latest
          imagePullPolicy: Always
          name: quiz-api
          env:
          - name: DB_LOGIN
            valueFrom:
              configMapKeyRef:
                name: quiz-api-conf
                key: DB_LOGIN
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-pass
                key: password
          - name: MYSQL_DB
            valueFrom:
              configMapKeyRef:
                name: quiz-api-conf
                key: MYSQL_DB
      restartPolicy: Always